name: schedule_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
# Flutter setup
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

# Client Http
  dio: ^4.0.6
  provider: ^6.0.3
  shared_preferences: ^2.0.15

# UX/UI
  flutter_svg: ^1.0.3
  loading_overlay: ^0.3.0
  another_flushbar: ^1.10.25

# State management
  mobx: ^2.0.7
  flutter_mobx: ^2.0.5
  google_fonts: ^3.0.1

#Maps
  geocoding: ^2.0.4

# Usefull tools
  flutter_keyboard_visibility: ^5.3.0
  mask_text_input_formatter: ^2.3.0
  flutter_dotenv: ^5.0.2
  pull_to_refresh: ^2.0.0
  flutter_native_splash: ^2.1.6
  intl: ^0.17.0
  timezone: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  mobx_codegen: ^2.0.7
  build_runner: ^2.1.10

#App icon
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

#App assets
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

#Splash configuration
flutter_native_splash:
  color: "#7052CC"
  android_12:
    icon_background_color: "#7052CC"
   


